name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (minimal)
      run: cargo build --verbose
    - name: Build (features)
      run : cargo build --verbose --all-features
    - name: Run tests (minimal)
      run: cargo test --verbose
    - name: Run tests (features)
      run: cargo test --verbose --all-features
